import 'package:get/get.dart';

import 'constants.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        STRKOREAN: {
          'home': '집',
          'company': '회사',
          'mylocation': '내 장소',
          'favorite': '즐겨찾기',
          'location': '장소',
          'location_permission_required':
              '현재 위치를 가져올 수 없습니다. 출발지를 직접 검색해 선택해주세요.',
          'point': '포인트',
          'cash': '현금',
          'min': '분',
          'sec': '초',
          'close': '닫기',
          'error_restart': '문제가 발생했습니다. 앱을 재시작 해주세요.',
          'language': '언어 변경',
          'Login_Header': '로그인',
          'Login_Text': '아이디와 비밀번호를\n입력해주세요 :)',
          'Login_ID': '아이디',
          'Login_ID_Hint': '아이디를 입력하세요',
          'Login_PWD': '비밀번호',
          'Login_PWD_Hint': '비밀번호를 입력하세요',
          'Login_Find_ID_PWD': '아이디/비밀번호 찾기',
          'Login_Register': '회원가입하러 가기',
          'Login_Button': '로그인하기',
          'login_error': '아이디 또는 비밀번호가 올바르지 않습니다',
          'register_header': '회원가입',
          'register_name': '이름',
          'register_firstname': '이름',
          'register_lastname': '성',
          'register_password': '비밀번호',
          'register_id': '아이디',
          'register_id_hint': '아이디를 입력하세요',
          'register_password_hint1': '비밀번호를 입력하세요',
          'register_password_hint2': '비밀번호를 재입력하세요',
          'register_password_validate': '영문 대/소문자, 숫자, 특수문자 20자 이내',
          'register_password_match': '비밀번호가 확인되었습니다',
          'register_password_not_match': '비밀번호가 일치하지 않습니다',
          'register_email': '이메일',
          'register_email_hint': '이메일을 입력하세요',
          'register_button': '가입하기',
          'register_error': '회원가입을 실패했습니다',
          'phone_header': '전화번호 인증',
          'phone_phone': '전화번호',
          'phone_edit': '수정하기',
          'phone_verificationcode': '인증번호받기',
          'phone_reverification': '인증번호 재전송',
          'phone_verify': '인증하기',
          'phone_error': '인증을 실패했습니다',
          'menu_event': '공지 및 이벤트',
          'menu_profile': '내 프로필',
          'menu_history': '탑승 내역',
          'menu_payment': '결제 관리',
          'menu_customerservice': '고객센터',
          'menu_setting': '설정',
          'home_where_are_you_going': '어디로 가시나요?',
          'home_set_start': '출발 위치를 설정해주세요.',
          'home_set_end': '목적지를 설정해주세요.',
          'map_pickup': '출발',
          'map_dropoff': '도착',
          'map_you': '내 위치',
          'map_driver': '기사님',
          'home_small_car': '1-4인',
          'home_large_car': '5인 이상',
          'home_payment': '결제수단',
          'home_payment_amount': '결제금액',
          'home_find_button': '택시 찾기',
          'home_estimated_time': '소요시간 ',
          'home_finding_driver': '주변 기사님을 찾고 있습니다...',
          'home_driver_coming': '기사님이 오고 있어요!',
          'home_riding': '탑승중',
          'home_payment_success': '결제가 완료된 상태입니다',
          'home_minutes_approximate': '약',
          'home_minutes_left': '후 도착',
          'tripsetting_header': '주소 설정',
          'tripsetting_recent': '최근내역',
          'payment_header': '결제수단',
          'payment_point': '내 포인트',
          'payment_useable_point': '사용 가능 포인트',
          'payment_add_point': '포인트 등록하기',
          'payment_card': '내 카드',
          'payment_add_card': '카드 추가하기',
          'card_default': '디폴트',
          'card_detail_not_complete': '카드 정보가 정확하지 않습니다.',
          'pointcoupon_add_header': '포인트 추가하기',
          'pointcoupon_add_button': '포인트 추가하기',
          'pointcoupon_add_coupon': '포인트 등록하기',
          'pointcoupon_add_point': '포인트 충전하기',
          'pointcoupon_add_coupon_hint': '코드를 작성해주세요',
          'pointcoupon_add_success': '포인트가 등록되었습니다',
          'pointcoupon_add_fail': '존재하는 코드번호가 아닙니다',
          'pointcard_add_point': '포인트 충전하기',
          'pointcard_amount': '충전금액',
          'pointcard_amount_hint': '금액을 입력해주세요',
          'pointcard_card': '충전계좌',
          'pointcard_add_card': '카드 추가하기',
          'pointcard_success': '포인트가 등록되었습니다',
          'pointcard_fail': '포인트 등록을 실패했습니다',
          'pointcard_button': '포인트 추가하기',
          'mylocation_add_button': '추가하기',
          'mylocation_hint': '저장 장소를 찾아주세요.',
          'mylocation_delete': '삭제',
          'mylocation_edit': '수정',
          'mylocation_add': '추가',
          'mylocation_address_help': '주소를 설정해주세요',
          'mylocation_add_location': '장소 추가하기',
          'trip_going_to_dest': '목적지에 가고 있어요',
          'trip_riding': '탑승중',
          'trip_map': '실시간 위치 보기',
          'trip_complete': '목적지 도착완료!',
          'trip_tip_add': '팁 추가하기',
          'trip_tip_other_amount': '다른 금액 입력하기',
          'trip_tip_okay': '확인',
          'trip_payment_amount': '결제금액',
          'trip_tip': '팁',
          'trip_payment_complete': '다음',
          'trip_report': '신고하기',
          'trip_report_body': '어떤 불편함을 겪으셨나요?',
          'trip_report_close': '닫기',
          'trip_report_hint': '기사님을 신고합니다.',
          'trip_refund': '환불받기',
          'trip_refund_body':
              '사유를 적어주시면 확인 후 환불 해드리겠습니다. \n신고하신 후에는 뒤로가기 버튼을 눌러 라이드를 취소해주세요.',
          'trip_refund_hint': '환불 사유가 무었인가요?',
          'trip_rate_button': '별점 주기',
          'trip_rate_alert': '본 평가는 기사님께 전달되지 않습니다.',
          'trip_rate_experience': '주행은 어떠셨나요??',
          'trip_cancel_button': '호출취소',
          'trip_cancel_title': '호출 취소',
          'trip_cancel_matching':
              '현재 택시를 호출 중이에요.\n정말 호출을 취소할까요?\n취소 시 운행비의 일부를 벌금으로\n낼 수 있습니다.',
          'trip_cancel_pickup':
              '기사님이 오고 있습니다.\n정말 호출을 취소할까요?\n취소 시 운행비의 일부를 벌금으로\n내게 됩니다.',
          'warning_no_default_card': '디폴트 카드가 없습니다',
          'warning_no_default_card_body': '카드를 추가해주세요',
          'trip_driver_cancel_home': '홈으로 가기',
          'trip_driver_cancel_header': '기사님 콜 취소',
          'trip_driver_cancel_body':
              '죄송합니다 기사님이 콜을 취소했습니다. \n다른 기사님을 원하시면 \n다른 기사님 찾기를 눌러주세요.',
          'trip_driver_cancel_newdriver': '다른 기사님 찾기',
          'term_agree': '동의하기',
          'terms_use': '[필수] U.S. Terms of Use',
          'terms_marketing': '[선택] 마케팅 정보 수신 동의',
          'terms_agree': '약관 동의',
          'terms_agree_body': '서비스 이용약관에 동의해주세요',
          'terms': '이용약관',
          'find_id_pwd': '아이디/비밀번호 찾기',
          'find_id': '아이디 찾기',
          'find_pwd': '비밀번호 찾기',
          'reset_pwd': '비밀번호 설정',
          'otp_wrong': '인증번호가 올바르지 않습니다',
          'otp_sent': '인증번호를 발송하였습니다',
          'otp_send_fail': '인증번호 발송을 실패하였습니다',
          'reset_pwd_fail': '비밀번호가 설정되지 않았습니다.',
          'reset_pwd_success': '비밀번호 설정을 성공하였습니다.',
          'event_header': '공지 및 이벤트',
          'customer_service_header': '고객센터',
          'trip_history_today': '오늘',
          'trip_history_week': '일주일',
          'trip_history_month': '이번달',
          'trip_history_last_month': '저번달',
          'trip_history_total': '전체',
          'trip_history_header': '탑승 내역',
          'profile_header': '내 정보',
          'profile_delete': '회원 탈퇴하기',
          'setting_header': '설정',
          'logout': '로그아웃',
          'notification': '알림 설정',
          'drivernumber': '번 기사님',
          'location_support': '뉴저지 또는 뉴욕에서 출발하는 운행을 지원합니다. 공항 운행도 이용할 수 있습니다.',
        },
        STRENGLISH: {
          'home': 'Home',
          'company': 'Work',
          'mylocation': 'Saved',
          'favorite': 'Favorite',
          'location': 'Location',
          'cash': 'Cash',
          'location_permission_required':
              'Current location is unavailable. Search and select your pickup manually.',
          'point': 'Points',
          'min': 'min',
          'sec': 'sec',
          'close': 'Close',
          'error_restart': 'Something went wrong. Please restart the app.',
          'language': 'Language',
          'Login_Header': 'Login',
          'Login_Text': 'Enter your ID and password',
          'Login_ID': 'ID',
          'Login_ID_Hint': 'Enter your ID',
          'Login_PWD': 'Password',
          'Login_PWD_Hint': 'Enter your password',
          'Login_Find_ID_PWD': 'Find ID/Password',
          'Login_Register': 'Register',
          'Login_Button': 'Login',
          'login_error': 'The ID or password is incorrect',
          'register_header': 'Create Account',
          'register_name': 'Name',
          'register_firstname': 'First name',
          'register_lastname': 'Last name',
          'register_password': 'Password',
          'register_id': 'ID',
          'register_id_hint': 'Enter an ID',
          'register_password_hint1': 'Enter a password',
          'register_password_hint2': 'Re-enter your password',
          'register_password_validate':
              'Use letters, numbers, and symbols (20 characters max)',
          'register_password_match': 'Passwords match',
          'register_password_not_match': 'Passwords do not match',
          'register_email': 'Email',
          'register_email_hint': 'Enter your email',
          'register_button': 'Create Account',
          'register_error': 'Account creation failed',
          'phone_header': 'Verify Phone Number',
          'phone_phone': 'Phone number',
          'phone_edit': 'Edit',
          'phone_verificationcode': 'Send verification code',
          'phone_reverification': 'Resend code',
          'phone_verify': 'Verify',
          'phone_error': 'Verification failed',
          'menu_event': 'Notices & Events',
          'menu_profile': 'Profile',
          'menu_history': 'Trip History',
          'menu_payment': 'Payment Methods',
          'menu_customerservice': 'Support',
          'menu_setting': 'Settings',
          'home_where_are_you_going': 'Where are you going?',
          'home_set_start': 'Set pickup location',
          'home_set_end': 'Set destination',
          'map_pickup': 'Pickup',
          'map_dropoff': 'Drop-off',
          'map_you': 'You',
          'map_driver': 'Driver',
          'home_small_car': '1-4 passengers',
          'home_large_car': '5+ passengers',
          'home_payment': 'Payment',
          'home_payment_amount': 'Fare',
          'home_find_button': 'Find a Taxi',
          'home_estimated_time': 'Estimated time ',
          'home_finding_driver': 'Finding a nearby driver...',
          'home_driver_coming': 'Your driver is on the way!',
          'home_riding': 'Trip in progress',
          'home_payment_success': 'Payment complete',
          'home_minutes_approximate': 'About',
          'home_minutes_left': 'away',
          'tripsetting_header': 'Set Route',
          'tripsetting_recent': 'Recent',
          'payment_header': 'Payment Method',
          'payment_point': 'My Points',
          'payment_useable_point': 'Available points',
          'payment_add_point': 'Add points',
          'payment_card': 'My Cards',
          'payment_add_card': 'Add card',
          'card_default': 'Default',
          'card_detail_not_complete': 'Please check the card details.',
          'pointcoupon_add_header': 'Add Points',
          'pointcoupon_add_button': 'Add Points',
          'pointcoupon_add_coupon': 'Redeem coupon',
          'pointcoupon_add_point': 'Buy points',
          'pointcoupon_add_coupon_hint': 'Enter coupon code',
          'pointcoupon_add_success': 'Points added',
          'pointcoupon_add_fail': 'Coupon code not found',
          'pointcard_add_point': 'Buy Points',
          'pointcard_amount': 'Amount',
          'pointcard_amount_hint': 'Enter an amount',
          'pointcard_card': 'Payment card',
          'pointcard_add_card': 'Add card',
          'pointcard_success': 'Points added',
          'pointcard_fail': 'Unable to add points',
          'pointcard_button': 'Add Points',
          'mylocation_add_button': 'Add',
          'mylocation_hint': 'Search for a saved location',
          'mylocation_delete': 'Delete',
          'mylocation_edit': 'Edit',
          'mylocation_add': 'Add',
          'mylocation_address_help': 'Choose a location',
          'mylocation_add_location': 'Add Location',
          'trip_going_to_dest': 'Heading to your destination',
          'trip_riding': 'Trip in progress',
          'trip_map': 'View live location',
          'trip_complete': 'You have arrived!',
          'trip_tip_add': 'Add a tip',
          'trip_tip_other_amount': 'Enter another amount',
          'trip_tip_okay': 'Confirm',
          'trip_payment_amount': 'Fare',
          'trip_tip': 'Tip',
          'trip_payment_complete': 'Continue',
          'trip_report': 'Report an issue',
          'trip_report_body': 'What went wrong?',
          'trip_report_close': 'Close',
          'trip_report_hint': 'Describe the issue with this trip',
          'trip_refund': 'Request a refund',
          'trip_refund_body':
              'Tell us what happened and we will review your request. Cancel the ride after submitting the report.',
          'trip_refund_hint': 'Reason for refund',
          'trip_rate_button': 'Rate Driver',
          'trip_rate_alert': 'Your rating is kept private.',
          'trip_rate_experience': 'How was your ride?',
          'trip_cancel_button': 'Cancel Ride',
          'trip_cancel_title': 'Cancel Ride',
          'trip_cancel_matching':
              'We are finding a driver. Cancel this request? A cancellation fee may apply.',
          'trip_cancel_pickup':
              'Your driver is on the way. Cancel this ride? A cancellation fee may apply.',
          'warning_no_default_card': 'No default card',
          'warning_no_default_card_body': 'Add a payment card to continue',
          'trip_driver_cancel_home': 'Back to Home',
          'trip_driver_cancel_header': 'Driver Cancelled',
          'trip_driver_cancel_body':
              'Your driver cancelled the ride. You can request another driver.',
          'trip_driver_cancel_newdriver': 'Find Another Driver',
          'term_agree': 'Agree',
          'terms_use': '[Required] U.S. Terms of Use',
          'terms_marketing': '[Optional] Marketing communications',
          'terms_agree': 'Terms Agreement',
          'terms_agree_body': 'Please agree to the terms of use',
          'terms': 'Terms of Use',
          'find_id_pwd': 'Find ID/Password',
          'find_id': 'Find ID',
          'find_pwd': 'Reset Password',
          'reset_pwd': 'Set Password',
          'otp_wrong': 'The verification code is incorrect',
          'otp_sent': 'Verification code sent',
          'otp_send_fail': 'Unable to send verification code',
          'reset_pwd_fail': 'Unable to update the password',
          'reset_pwd_success': 'Password updated',
          'event_header': 'Notices & Events',
          'customer_service_header': 'Support',
          'trip_history_today': 'Today',
          'trip_history_week': '7 Days',
          'trip_history_month': 'This Month',
          'trip_history_last_month': 'Last Month',
          'trip_history_total': 'All',
          'trip_history_header': 'Trip History',
          'profile_header': 'Profile',
          'profile_delete': 'Delete account',
          'setting_header': 'Settings',
          'logout': 'Log Out',
          'notification': 'Notifications',
          'drivernumber': 'Driver',
          'location_support':
              'Service is available for trips starting in New Jersey or New York, including airport trips.',
        },
      };
}
