// <auto-generated />
using System;
using KoreanTaxi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KoreanTaxi.Migrations
{
    [DbContext(typeof(TaxiDbContext))]
    partial class TaxiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KoreanTaxi.Models.BackgroundHistory", b =>
                {
                    b.Property<long>("BackgroundHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("backgroundhistoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BackgroundHistoryID"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<int>("CustomerQueueCount")
                        .HasColumnType("integer")
                        .HasColumnName("customerqueuecount");

                    b.Property<int>("DriverQueueCount")
                        .HasColumnType("integer")
                        .HasColumnName("driverqueuecount");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("ErrorAmount")
                        .HasColumnType("integer")
                        .HasColumnName("erroramount");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("issuccess");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process");

                    b.Property<int>("SuccessAmount")
                        .HasColumnType("integer")
                        .HasColumnName("successamount");

                    b.HasKey("BackgroundHistoryID")
                        .HasName("pk_backgroundhistories");

                    b.ToTable("backgroundhistories", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Company", b =>
                {
                    b.Property<long>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyID"));

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contactname");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifieddatetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<int>("TimeZone")
                        .HasColumnType("integer")
                        .HasColumnName("timezone");

                    b.Property<string>("Zip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zip");

                    b.HasKey("CompanyID")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyCustomerPhoneNumber", b =>
                {
                    b.Property<long>("CompanyCustomerPhoneNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companycustomerphonenumberid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyCustomerPhoneNumberID"));

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customername");

                    b.Property<long?>("GoogleLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("googlelocationid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phonenumber");

                    b.HasKey("CompanyCustomerPhoneNumberID")
                        .HasName("pk_companycustomerphonenumbers");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_companycustomerphonenumbers_companyid");

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("ix_companycustomerphonenumbers_customername");

                    b.HasIndex("GoogleLocationID")
                        .HasDatabaseName("ix_companycustomerphonenumbers_googlelocationid");

                    b.ToTable("companycustomerphonenumbers", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyFrequentLocation", b =>
                {
                    b.Property<long>("CompanyFrequentLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companyfrequentlocationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyFrequentLocationID"));

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long>("GoogleLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("googlelocationid");

                    b.HasKey("CompanyFrequentLocationID")
                        .HasName("pk_companyfrequentlocations");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_companyfrequentlocations_companyid");

                    b.HasIndex("GoogleLocationID")
                        .HasDatabaseName("ix_companyfrequentlocations_googlelocationid");

                    b.ToTable("companyfrequentlocations", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyGoogleLocation", b =>
                {
                    b.Property<long>("CompanyGoogleLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companygooglelocationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyGoogleLocationID"));

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long>("GoogleLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("googlelocationid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("CompanyGoogleLocationID")
                        .HasName("pk_companygooglelocations");

                    b.HasIndex("GoogleLocationID")
                        .IsUnique()
                        .HasDatabaseName("ix_companygooglelocations_googlelocationid");

                    b.HasIndex("CompanyID", "GoogleLocationID")
                        .IsUnique()
                        .HasDatabaseName("ix_companygooglelocations_companyid_googlelocationid");

                    b.ToTable("companygooglelocations", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyOperatingState", b =>
                {
                    b.Property<long>("CompanyOperatingStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companyoperatingstateid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyOperatingStateID"));

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<int>("FromState")
                        .HasColumnType("integer")
                        .HasColumnName("fromstate");

                    b.Property<int?>("ToState")
                        .HasColumnType("integer")
                        .HasColumnName("tostate");

                    b.HasKey("CompanyOperatingStateID")
                        .HasName("pk_companyoperatingstates");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_companyoperatingstates_companyid");

                    b.HasIndex("FromState")
                        .HasDatabaseName("ix_companyoperatingstates_fromstate");

                    b.ToTable("companyoperatingstates", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyTripPrice", b =>
                {
                    b.Property<long>("CompanyTripPriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companytrippriceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyTripPriceID"));

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fromcity");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tocity");

                    b.HasKey("CompanyTripPriceID")
                        .HasName("pk_companytripprices");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_companytripprices_companyid");

                    b.ToTable("companytripprices", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyUser", b =>
                {
                    b.Property<long>("CompanyUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companyuserid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyUserID"));

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<long>("LoginUserID")
                        .HasColumnType("bigint")
                        .HasColumnName("loginuserid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("CompanyUserID")
                        .HasName("pk_companyusers");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_companyusers_companyid");

                    b.HasIndex("LoginUserID")
                        .IsUnique()
                        .HasDatabaseName("ix_companyusers_loginuserid");

                    b.ToTable("companyusers", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Coupon", b =>
                {
                    b.Property<long>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("couponid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CouponID"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddate");

                    b.Property<long?>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.HasKey("CouponID")
                        .HasName("pk_coupons");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_coupons_code");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("ix_coupons_customerid");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerID"));

                    b.Property<string>("AuthNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("authnumber");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long?>("DefaultCardID")
                        .HasColumnType("bigint")
                        .HasColumnName("defaultcardid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("isverified");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lastname");

                    b.Property<long>("LoginUserID")
                        .HasColumnType("bigint")
                        .HasColumnName("loginuserid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phonenumber");

                    b.Property<decimal>("Point")
                        .HasColumnType("numeric")
                        .HasColumnName("point");

                    b.Property<string>("StripeCustomerID")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripecustomerid");

                    b.Property<bool>("Term1")
                        .HasColumnType("boolean")
                        .HasColumnName("term1");

                    b.Property<bool>("Term2")
                        .HasColumnType("boolean")
                        .HasColumnName("term2");

                    b.Property<int>("TimeZone")
                        .HasColumnType("integer")
                        .HasColumnName("timezone");

                    b.HasKey("CustomerID")
                        .HasName("pk_customers");

                    b.HasIndex("LoginUserID")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_loginuserid");

                    b.HasIndex("PhoneNumber", "IsVerified")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_phonenumber_isverified")
                        .HasFilter("IsVerified IS TRUE");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerCard", b =>
                {
                    b.Property<long>("CustomerCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customercardid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerCardID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.Property<int>("ExpirationMonth")
                        .HasColumnType("integer")
                        .HasColumnName("expirationmonth");

                    b.Property<int>("ExpirationYear")
                        .HasColumnType("integer")
                        .HasColumnName("expirationyear");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("isremoved");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last4");

                    b.Property<string>("PaymentMethodID")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("paymentmethodid");

                    b.HasKey("CustomerCardID")
                        .HasName("pk_customercards");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("ix_customercards_customerid");

                    b.ToTable("customercards", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerQueue", b =>
                {
                    b.Property<long>("CustomerQueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customerqueueid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerQueueID"));

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long?>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.Property<int>("QueueStatus")
                        .HasColumnType("integer")
                        .HasColumnName("queuestatus");

                    b.Property<long>("TripID")
                        .HasColumnType("bigint")
                        .HasColumnName("tripid");

                    b.HasKey("CustomerQueueID")
                        .HasName("pk_customerqueues");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_customerqueues_companyid");

                    b.HasIndex("CreatedDateTime")
                        .IsDescending()
                        .HasDatabaseName("ix_customerqueues_createddatetime");

                    b.HasIndex("CustomerID")
                        .IsUnique()
                        .HasDatabaseName("ix_customerqueues_customerid")
                        .HasFilter("CustomerID is not null");

                    b.HasIndex("QueueStatus")
                        .HasDatabaseName("ix_customerqueues_queuestatus");

                    b.HasIndex("TripID")
                        .IsUnique()
                        .HasDatabaseName("ix_customerqueues_tripid");

                    b.ToTable("customerqueues", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerSavedLocation", b =>
                {
                    b.Property<long>("CustomerSavedLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customersavedlocationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerSavedLocationID"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.Property<long>("GoogleLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("googlelocationid");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("CustomerSavedLocationID")
                        .HasName("pk_customersavedlocations");

                    b.HasIndex("CreatedDateTime")
                        .HasDatabaseName("ix_customersavedlocations_createddatetime");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("ix_customersavedlocations_customerid");

                    b.HasIndex("GoogleLocationID")
                        .HasDatabaseName("ix_customersavedlocations_googlelocationid");

                    b.HasIndex("CustomerID", "GoogleLocationID")
                        .IsUnique()
                        .HasDatabaseName("ix_customersavedlocations_customerid_googlelocationid");

                    b.ToTable("customersavedlocations", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerSearchHistory", b =>
                {
                    b.Property<long>("CustomerSearchHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customersearchhistoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerSearchHistoryID"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.Property<long>("GoogleLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("googlelocationid");

                    b.HasKey("CustomerSearchHistoryID")
                        .HasName("pk_customersearchhistories");

                    b.HasIndex("CreatedDateTime")
                        .HasDatabaseName("ix_customersearchhistories_createddatetime");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("ix_customersearchhistories_customerid");

                    b.HasIndex("GoogleLocationID")
                        .HasDatabaseName("ix_customersearchhistories_googlelocationid");

                    b.HasIndex("CustomerID", "GoogleLocationID")
                        .IsUnique()
                        .HasDatabaseName("ix_customersearchhistories_customerid_googlelocationid");

                    b.ToTable("customersearchhistories", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Driver", b =>
                {
                    b.Property<long>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("driverid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DriverID"));

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer")
                        .HasColumnName("drivernumber");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsAppTaxi")
                        .HasColumnType("boolean")
                        .HasColumnName("isapptaxi");

                    b.Property<DateTime?>("IsArchived")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isarchived");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lastname");

                    b.Property<long>("LoginUserID")
                        .HasColumnType("bigint")
                        .HasColumnName("loginuserid");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("map");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("TLCApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("tlcapproved");

                    b.HasKey("DriverID")
                        .HasName("pk_drivers");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_drivers_companyid");

                    b.HasIndex("LoginUserID")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_loginuserid");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_drivers_phonenumber");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.DriverQueue", b =>
                {
                    b.Property<long>("DriverQueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("driverqueueid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DriverQueueID"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long?>("CustomerQueueID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerqueueid");

                    b.Property<int?>("DeclinedCount")
                        .HasColumnType("integer")
                        .HasColumnName("declinedcount");

                    b.Property<DateTime>("DeclinedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declinedtime");

                    b.Property<long>("DriverID")
                        .HasColumnType("bigint")
                        .HasColumnName("driverid");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<int>("QueueStatus")
                        .HasColumnType("integer")
                        .HasColumnName("queuestatus");

                    b.Property<long?>("TripID")
                        .HasColumnType("bigint")
                        .HasColumnName("tripid");

                    b.HasKey("DriverQueueID")
                        .HasName("pk_driverqueues");

                    b.HasIndex("CreatedDateTime")
                        .IsDescending()
                        .HasDatabaseName("ix_driverqueues_createddatetime");

                    b.HasIndex("CustomerQueueID")
                        .HasDatabaseName("ix_driverqueues_customerqueueid");

                    b.HasIndex("DriverID")
                        .IsUnique()
                        .HasDatabaseName("ix_driverqueues_driverid")
                        .HasFilter("DriverID is not null");

                    b.HasIndex("QueueStatus")
                        .HasDatabaseName("ix_driverqueues_queuestatus");

                    b.HasIndex("TripID")
                        .HasDatabaseName("ix_driverqueues_tripid");

                    b.ToTable("driverqueues", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.DriverQueueRejectedCustomerQueue", b =>
                {
                    b.Property<long>("DriverQueueRejectedCustomerQueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("driverqueuerejectedcustomerqueueid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DriverQueueRejectedCustomerQueueID"));

                    b.Property<long>("CustomerQueueID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerqueueid");

                    b.Property<long>("DriverQueueID")
                        .HasColumnType("bigint")
                        .HasColumnName("driverqueueid");

                    b.HasKey("DriverQueueRejectedCustomerQueueID")
                        .HasName("pk_driverqueuerejectedcustomerqueues");

                    b.HasIndex("DriverQueueID")
                        .HasDatabaseName("ix_driverqueuerejectedcustomerqueues_driverqueueid");

                    b.ToTable("driverqueuerejectedcustomerqueues", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.DriverRating", b =>
                {
                    b.Property<long>("DriverRatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("driverratingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DriverRatingID"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.Property<long>("DriverID")
                        .HasColumnType("bigint")
                        .HasColumnName("driverid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<long>("TripID")
                        .HasColumnType("bigint")
                        .HasColumnName("tripid");

                    b.HasKey("DriverRatingID")
                        .HasName("pk_driverratings");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("ix_driverratings_customerid");

                    b.HasIndex("DriverID")
                        .HasDatabaseName("ix_driverratings_driverid");

                    b.HasIndex("TripID")
                        .HasDatabaseName("ix_driverratings_tripid");

                    b.ToTable("driverratings", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Event", b =>
                {
                    b.Property<long>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eventid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventID"));

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("eventdescription");

                    b.Property<DateTime>("EventEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eventenddate");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("eventname");

                    b.Property<DateTime>("EventStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eventstartdate");

                    b.HasKey("EventID")
                        .HasName("pk_events");

                    b.HasIndex("EventStartDate", "EventEndDate")
                        .IsUnique()
                        .HasDatabaseName("ix_events_eventstartdate_eventenddate");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.GoogleLocation", b =>
                {
                    b.Property<long>("GoogleLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("googlelocationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GoogleLocationID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("latitude");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("locationtype");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("GoogleLocationID")
                        .HasName("pk_googlelocations");

                    b.HasIndex("Name", "Address")
                        .IsUnique()
                        .HasDatabaseName("ix_googlelocations_name_address");

                    b.ToTable("googlelocations", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.LoginUser", b =>
                {
                    b.Property<long>("LoginUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("loginuserid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LoginUserID"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastlogindatetime");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifieddatetime");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea")
                        .HasColumnName("passwordhash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("passwordsalt");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refreshtoken");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("TokenCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tokencreated");

                    b.Property<DateTime?>("TokenExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tokenexpires");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("LoginUserID")
                        .HasName("pk_loginusers");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_loginusers_username");

                    b.ToTable("loginusers", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Payment", b =>
                {
                    b.Property<long>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("paymentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentID"));

                    b.Property<decimal>("CardAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cardamount");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long?>("CustomerCardID")
                        .HasColumnType("bigint")
                        .HasColumnName("customercardid");

                    b.Property<string>("PaymentIntentID")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("paymentintentid");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("paymentstatus");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("paymenttype");

                    b.Property<decimal>("PointAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("pointamount");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tipamount");

                    b.Property<long>("TripID")
                        .HasColumnType("bigint")
                        .HasColumnName("tripid");

                    b.HasKey("PaymentID")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerCardID")
                        .HasDatabaseName("ix_payments_customercardid");

                    b.HasIndex("PaymentStatus")
                        .HasDatabaseName("ix_payments_paymentstatus");

                    b.HasIndex("PaymentType")
                        .HasDatabaseName("ix_payments_paymenttype");

                    b.HasIndex("TripID")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_tripid");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.PointAddHistory", b =>
                {
                    b.Property<long>("PointAddHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pointaddhistoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PointAddHistoryID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.Property<int>("PointType")
                        .HasColumnType("integer")
                        .HasColumnName("pointtype");

                    b.HasKey("PointAddHistoryID")
                        .HasName("pk_pointaddhistories");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("ix_pointaddhistories_customerid");

                    b.ToTable("pointaddhistories", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.StateDefaultLocation", b =>
                {
                    b.Property<long>("StateDefaultLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("statedefaultlocationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StateDefaultLocationID"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(8,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("StateDefaultLocationID")
                        .HasName("pk_statedefaultlocations");

                    b.HasIndex("State")
                        .IsUnique()
                        .HasDatabaseName("ix_statedefaultlocations_state");

                    b.ToTable("statedefaultlocations", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.StateFee", b =>
                {
                    b.Property<long>("StateFeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("statefeeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StateFeeID"));

                    b.Property<int>("CalculationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("calculationmethod");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<int?>("FromState")
                        .HasColumnType("integer")
                        .HasColumnName("fromstate");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("locationtype");

                    b.Property<int?>("ToState")
                        .HasColumnType("integer")
                        .HasColumnName("tostate");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("StateFeeID")
                        .HasName("pk_statefees");

                    b.HasIndex("FromState")
                        .HasDatabaseName("ix_statefees_fromstate");

                    b.HasIndex("ToState")
                        .HasDatabaseName("ix_statefees_tostate");

                    b.ToTable("statefees", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Taxi", b =>
                {
                    b.Property<long>("TaxiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("taxiid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TaxiID"));

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long?>("DriverID")
                        .HasColumnType("bigint")
                        .HasColumnName("driverid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("licenseplate");

                    b.Property<int>("Make")
                        .HasColumnType("integer")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.HasKey("TaxiID")
                        .HasName("pk_taxis");

                    b.HasIndex("DriverID")
                        .IsUnique()
                        .HasDatabaseName("ix_taxis_driverid");

                    b.ToTable("taxis", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.Trip", b =>
                {
                    b.Property<long>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tripid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TripID"));

                    b.Property<string>("AlcoholPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alcoholphonenumber");

                    b.Property<long?>("AlcoholTripID")
                        .HasColumnType("bigint")
                        .HasColumnName("alcoholtripid");

                    b.Property<int?>("CalledTaxiSize")
                        .HasColumnType("integer")
                        .HasColumnName("calledtaxisize");

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint")
                        .HasColumnName("companyid");

                    b.Property<decimal>("CompanyTripAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("companytripamount");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedtime");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddatetime");

                    b.Property<long?>("CustomerID")
                        .HasColumnType("bigint")
                        .HasColumnName("customerid");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customerphonenumber");

                    b.Property<long?>("DriverID")
                        .HasColumnType("bigint")
                        .HasColumnName("driverid");

                    b.Property<long?>("DropoffLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("dropofflocationid");

                    b.Property<decimal>("LargeStateFeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("largestatefeeamount");

                    b.Property<decimal>("Mileage")
                        .HasColumnType("numeric")
                        .HasColumnName("mileage");

                    b.Property<decimal>("MileageAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("mileageamount");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<long>("PickupLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("pickuplocationid");

                    b.Property<decimal>("SmallStateFeeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("smallstatefeeamount");

                    b.Property<decimal>("TollAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tollamount");

                    b.Property<int>("TripStatus")
                        .HasColumnType("integer")
                        .HasColumnName("tripstatus");

                    b.Property<int>("TripType")
                        .HasColumnType("integer")
                        .HasColumnName("triptype");

                    b.HasKey("TripID")
                        .HasName("pk_trips");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("ix_trips_companyid");

                    b.HasIndex("CompletedTime")
                        .HasDatabaseName("ix_trips_completedtime");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("ix_trips_customerid");

                    b.HasIndex("DriverID")
                        .HasDatabaseName("ix_trips_driverid");

                    b.HasIndex("DropoffLocationID")
                        .HasDatabaseName("ix_trips_dropofflocationid");

                    b.HasIndex("TripStatus")
                        .HasDatabaseName("ix_trips_tripstatus");

                    b.HasIndex("PickupLocationID", "DropoffLocationID")
                        .HasDatabaseName("ix_trips_pickuplocationid_dropofflocationid");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.TripPriceDetail", b =>
                {
                    b.Property<long>("TripPriceDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("trippricedetailid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TripPriceDetailID"));

                    b.Property<decimal>("LargeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("largeamount");

                    b.Property<decimal>("SmallAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("smallamount");

                    b.Property<long>("StateFeeID")
                        .HasColumnType("bigint")
                        .HasColumnName("statefeeid");

                    b.Property<long>("TripID")
                        .HasColumnType("bigint")
                        .HasColumnName("tripid");

                    b.HasKey("TripPriceDetailID")
                        .HasName("pk_trippricedetails");

                    b.HasIndex("StateFeeID")
                        .HasDatabaseName("ix_trippricedetails_statefeeid");

                    b.HasIndex("TripID")
                        .HasDatabaseName("ix_trippricedetails_tripid");

                    b.ToTable("trippricedetails", (string)null);
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyCustomerPhoneNumber", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany("CompanyCustomerPhoneNumbers")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companycustomerphonenumbers_companies_companyid");

                    b.HasOne("KoreanTaxi.Models.GoogleLocation", "GoogleLocation")
                        .WithMany()
                        .HasForeignKey("GoogleLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_companycustomerphonenumbers_googlelocations_googlelocationid");

                    b.Navigation("Company");

                    b.Navigation("GoogleLocation");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyFrequentLocation", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany("CompanyFrequentLocations")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companyfrequentlocations_companies_companyid");

                    b.HasOne("KoreanTaxi.Models.GoogleLocation", "GoogleLocation")
                        .WithMany()
                        .HasForeignKey("GoogleLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companyfrequentlocations_googlelocations_googlelocationid");

                    b.Navigation("Company");

                    b.Navigation("GoogleLocation");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyGoogleLocation", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_companygooglelocations_companies_companyid");

                    b.HasOne("KoreanTaxi.Models.GoogleLocation", "GoogleLocation")
                        .WithOne("CompanyGoogleLocation")
                        .HasForeignKey("KoreanTaxi.Models.CompanyGoogleLocation", "GoogleLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companygooglelocations_googlelocations_googlelocationid");

                    b.Navigation("Company");

                    b.Navigation("GoogleLocation");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyOperatingState", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany("CompanyOperatingStates")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companyoperatingstates_companies_companyid");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyTripPrice", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companytripprices_companies_companyid");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CompanyUser", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companyusers_companies_companyid");

                    b.HasOne("KoreanTaxi.Models.LoginUser", "LoginUser")
                        .WithMany()
                        .HasForeignKey("LoginUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companyusers_loginusers_loginuserid");

                    b.Navigation("Company");

                    b.Navigation("LoginUser");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Customer", b =>
                {
                    b.HasOne("KoreanTaxi.Models.LoginUser", "LoginUser")
                        .WithMany()
                        .HasForeignKey("LoginUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_loginusers_loginuserid");

                    b.Navigation("LoginUser");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerCard", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Customer", "Customer")
                        .WithMany("CustomerCards")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customercards_customers_customerid");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerQueue", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany("CompanyQueues")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customerqueues_companies_companyid");

                    b.HasOne("KoreanTaxi.Models.Customer", "Customer")
                        .WithOne("CustomerQueue")
                        .HasForeignKey("KoreanTaxi.Models.CustomerQueue", "CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customerqueues_customers_customerid");

                    b.HasOne("KoreanTaxi.Models.Trip", "Trip")
                        .WithOne("CustomerQueue")
                        .HasForeignKey("KoreanTaxi.Models.CustomerQueue", "TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customerqueues_trips_tripid");

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerSavedLocation", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Customer", "Customer")
                        .WithMany("CustomerSavedLocations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customersavedlocations_customers_customerid");

                    b.HasOne("KoreanTaxi.Models.GoogleLocation", "GoogleLocation")
                        .WithMany()
                        .HasForeignKey("GoogleLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customersavedlocations_googlelocations_googlelocationid");

                    b.Navigation("Customer");

                    b.Navigation("GoogleLocation");
                });

            modelBuilder.Entity("KoreanTaxi.Models.CustomerSearchHistory", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Customer", "Customer")
                        .WithMany("CustomerSearchHistories")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customersearchhistories_customers_customerid");

                    b.HasOne("KoreanTaxi.Models.GoogleLocation", "GoogleLocation")
                        .WithMany()
                        .HasForeignKey("GoogleLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customersearchhistories_googlelocations_googlelocationid");

                    b.Navigation("Customer");

                    b.Navigation("GoogleLocation");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Driver", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany("Drivers")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drivers_companies_companyid");

                    b.HasOne("KoreanTaxi.Models.LoginUser", "LoginUser")
                        .WithMany()
                        .HasForeignKey("LoginUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drivers_loginusers_loginuserid");

                    b.Navigation("Company");

                    b.Navigation("LoginUser");
                });

            modelBuilder.Entity("KoreanTaxi.Models.DriverQueue", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Driver", "Driver")
                        .WithOne("DriverQueue")
                        .HasForeignKey("KoreanTaxi.Models.DriverQueue", "DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driverqueues_drivers_driverid");

                    b.HasOne("KoreanTaxi.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_driverqueues_trips_tripid");

                    b.Navigation("Driver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("KoreanTaxi.Models.DriverQueueRejectedCustomerQueue", b =>
                {
                    b.HasOne("KoreanTaxi.Models.DriverQueue", "DriverQueue")
                        .WithMany("DriverQueueRejectedCustomerQueues")
                        .HasForeignKey("DriverQueueID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driverqueuerejectedcustomerqueues_driverqueues_driverqueueid");

                    b.Navigation("DriverQueue");
                });

            modelBuilder.Entity("KoreanTaxi.Models.DriverRating", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driverratings_customers_customerid");

                    b.HasOne("KoreanTaxi.Models.Driver", "Driver")
                        .WithMany("DriverRatings")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driverratings_drivers_driverid");

                    b.HasOne("KoreanTaxi.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driverratings_trips_tripid");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Payment", b =>
                {
                    b.HasOne("KoreanTaxi.Models.CustomerCard", "CustomerCard")
                        .WithMany()
                        .HasForeignKey("CustomerCardID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_customercards_customercardid");

                    b.HasOne("KoreanTaxi.Models.Trip", "Trip")
                        .WithOne("Payment")
                        .HasForeignKey("KoreanTaxi.Models.Payment", "TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_trips_tripid");

                    b.Navigation("CustomerCard");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("KoreanTaxi.Models.PointAddHistory", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pointaddhistories_customers_customerid");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Taxi", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Driver", "Driver")
                        .WithOne("Taxi")
                        .HasForeignKey("KoreanTaxi.Models.Taxi", "DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_taxis_drivers_driverid");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Trip", b =>
                {
                    b.HasOne("KoreanTaxi.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trips_companies_companyid");

                    b.HasOne("KoreanTaxi.Models.Customer", "Customer")
                        .WithMany("Trips")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trips_customers_customerid");

                    b.HasOne("KoreanTaxi.Models.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trips_drivers_driverid");

                    b.HasOne("KoreanTaxi.Models.GoogleLocation", "DropoffLocation")
                        .WithMany()
                        .HasForeignKey("DropoffLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trips_googlelocations_dropofflocationid");

                    b.HasOne("KoreanTaxi.Models.GoogleLocation", "PickupLocation")
                        .WithMany()
                        .HasForeignKey("PickupLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_googlelocations_pickuplocationid");

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("DropoffLocation");

                    b.Navigation("PickupLocation");
                });

            modelBuilder.Entity("KoreanTaxi.Models.TripPriceDetail", b =>
                {
                    b.HasOne("KoreanTaxi.Models.StateFee", "StateFee")
                        .WithMany()
                        .HasForeignKey("StateFeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trippricedetails_statefees_statefeeid");

                    b.HasOne("KoreanTaxi.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trippricedetails_trips_tripid");

                    b.Navigation("StateFee");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Company", b =>
                {
                    b.Navigation("CompanyCustomerPhoneNumbers");

                    b.Navigation("CompanyFrequentLocations");

                    b.Navigation("CompanyOperatingStates");

                    b.Navigation("CompanyQueues");

                    b.Navigation("CompanyUsers");

                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Customer", b =>
                {
                    b.Navigation("CustomerCards");

                    b.Navigation("CustomerQueue");

                    b.Navigation("CustomerSavedLocations");

                    b.Navigation("CustomerSearchHistories");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Driver", b =>
                {
                    b.Navigation("DriverQueue");

                    b.Navigation("DriverRatings");

                    b.Navigation("Taxi");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("KoreanTaxi.Models.DriverQueue", b =>
                {
                    b.Navigation("DriverQueueRejectedCustomerQueues");
                });

            modelBuilder.Entity("KoreanTaxi.Models.GoogleLocation", b =>
                {
                    b.Navigation("CompanyGoogleLocation");
                });

            modelBuilder.Entity("KoreanTaxi.Models.Trip", b =>
                {
                    b.Navigation("CustomerQueue");

                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
