import 'package:get/get.dart';

import 'constants.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        STRKOREAN: {
          'cancel': '취소',
          'okay': '확인',
          'Login_Header': '로그인',
          'Login_Text': '아이디와 비밀번호를\n입력해주세요 :)',
          'Login_ID': '아이디',
          'Login_ID_Hint': '아이디를 입력하세요',
          'Login_PWD': '비밀번호',
          'Login_PWD_Hint': '비밀번호를 입력하세요',
          'Login_Find_ID_PWD': '아이디/비밀번호 찾기',
          'Login_Button': '로그인하기',
          'Home_Profile': '나의 프로필',
          'Home_Change': '변경하기',
          'Home_Car_Info': '차량 정보',
          'Home_Recent_History': '최근 내역',
          'Home_Show_More': '더보기',
          'Home_Start': '출근하기',
          'Trip_Waiting': '콜 대기 중',
          'Trip_Stop': '콜 멈추기',
          'Trip_Stop_Message': '콜을 멈추면 대기열에서 나가져요. \n 정말 콜 대기를 취소할까요?',
          'Trip_Stop_Dialog_Button': '대기취소',
          'Trip_Reject': '거절하기',
          'Trip_Reject_Message': '3번 거절하면 대기열에서 밀려나요. \n 정말 이번 콜을 거절할까요?',
          'Trip_Call': '콜',
          'Trip_Call_Received': '이 도착했어요!',
          'Trip_Start_Location': '출발지',
          'Trip_End_Location': '도착지',
          'Trip_Accept': '수락하기',
          'Trip_Auto_Decline': '@seconds초 후 자동 거절',
          'Trip_Alert_Message': '콜 3번 거절시 대기열에서 밀려납니다.',
          'trip_customer': '손님',
          'trip_going': '에게 가고있어요!',
          'trip_customer_name': '성함',
          'trip_view_customer_map': '손님 위치 보기',
          'trip_start': '주행 시작하기',
          'trip_customer_inside': '손님을 태우셨나요?',
          'trip_customer_confirm_message':
              '손님이 타시고 난 후에 누르셔야 정상적인 \n결제가 이루어집니다.',
          'trip_customer_noshow': '손님이 안계시나요?',
          'trip_customer_noshow_short': '손님 없음',
          'trip_customer_noshow_body': '기다려도 손님이 나타나지 않았을 \n시에만 취소해주세요.',
          'trip_airport': '공항 콜을 취소하시나요?',
          'trip_airport_body': '취소시 다시 대기 순번으로 돌아가게 됩니다.',
          'trip_dest': '목적지',
          'trip_dest_going': '에 가고 있어요!',
          'trip_customer_onboard': '손님 탑승중',
          'trip_pickup': '픽업장소',
          'trip_amount': '결제금액',
          'trip_dest_map': '실시간 위치보기',
          'trip_card': '현금 수금이 필요하지 않습니다.',
          'trip_cash': '운행 완료 후 승객에게 요금을 받아주세요.',
          'trip_voucher': '바우처 콜입니다.',
          'trip_alcohol1': '대리운전1 입니다.',
          'trip_alcohol2': '대리운전2 입니다.',
          'trip_complete': '주행 완료하기',
          'trip_complete_modal_title': '주행을 완료하셨나요?',
          'trip_complete_modal_body': '완료하시면 더 이상 라이드 정보를 \n 볼 수 없습니다.',
          'trip_rest': '휴식하기',
          'trip_wait': '콜 대기',
          'trip_wait_body': '확인을 누르면 대기열에 들어가게 됩니다. \n 콜 대기를 시작할까요?',
          'trip_complete!': '주행 완료!',
          'trip_safe_thanks': '안전한 주행해주셔서 \n 감사합니다.',
          'trip_customer_cancel': '손님 호출 취소',
          'trip_customer_cancel_body': '손님이 호출취소를 눌렀어요. \n 다시 콜을 잡아볼까요?',
          'Dialog_Close': '닫기',
          'trip_history_header': '나의 내역',
          'trip_history_earned': '총 수입',
          'trip_history_today': '오늘',
          'trip_history_week': '일주일',
          'trip_history_month': '이번달',
          'trip_history_last_month': '저번달',
          'trip_history_total': '전체',
          'dest_location_header': '목적지를 정해주세요',
          'dest_location_hint': '목적지를 입력하세요.',
          'dest_location_button': '등록하기',
          'drivernumber': '번 기사님',
          'driver_number_label': '@number번 기사님',
          'Home_Today': '오늘',
          'Home_Logout': '로그아웃',
          'note': '노트',
          'choose_map': '사용하실 맵을 골라주세요.',
          'location_permission': '위치 정보 사용을 동의해주세요',
          'location_permission_retry': '현재 위치 사용하기',
          'location_permission_description': '설정에서 위치 정보 항상 공유하기를 선택해주세요',
          'appsetting': '설정하기',
        },
        STRENGLISH: {
          'cancel': 'Cancel',
          'okay': 'Confirm',
          'Login_Header': 'Login',
          'Login_Text': 'Enter your ID and password',
          'Login_ID': 'ID',
          'Login_ID_Hint': 'Enter your ID',
          'Login_PWD': 'Password',
          'Login_PWD_Hint': 'Enter your password',
          'Login_Find_ID_PWD': 'Find ID/Password',
          'Login_Register': 'Register',
          'Login_Button': 'Login',
          'Home_Profile': 'My Profile',
          'Home_Change': 'Update',
          'Home_Car_Info': 'Vehicle Info',
          'Home_Recent_History': 'Recent History',
          'Home_Show_More': 'More',
          'Home_Start': 'Start',
          'Trip_Waiting': 'Waiting for requests',
          'Trip_Stop': 'Stop Requests',
          'Trip_Stop_Message':
              'Stopping will remove you from the driver queue. Stop waiting for requests?',
          'Trip_Stop_Dialog_Button': 'Stop Waiting',
          'Trip_Reject': 'Decline',
          'Trip_Reject_Message':
              'Declining three requests moves you back in the queue. Decline this request?',
          'Trip_Call': 'Ride request ',
          'Trip_Call_Received': 'received!',
          'Trip_Start_Location': 'Pickup',
          'Trip_End_Location': 'Destination',
          'Trip_Accept': 'Accept',
          'Trip_Auto_Decline': 'Auto-decline in @seconds sec',
          'Trip_Alert_Message':
              'After three declines, you will move back in the queue.',
          'trip_customer': 'Passenger ',
          'trip_going': 'pickup in progress',
          'trip_customer_name': 'Name',
          'trip_view_customer_map': 'View pickup location',
          'trip_start': 'Start Trip',
          'trip_customer_inside': 'Is the passenger in the vehicle?',
          'trip_customer_confirm_message':
              'Start the trip only after the passenger is in the vehicle so payment is calculated correctly.',
          'trip_customer_noshow': 'Passenger not present?',
          'trip_customer_noshow_short': 'No-show',
          'trip_customer_noshow_body':
              'Cancel only after waiting at the pickup location.',
          'trip_airport': 'Cancel airport request?',
          'trip_airport_body':
              'You will return to the airport queue after cancellation.',
          'trip_dest': 'Destination ',
          'trip_dest_going': 'trip in progress',
          'trip_customer_onboard': 'Passenger onboard',
          'trip_pickup': 'Pickup',
          'trip_amount': 'Fare',
          'trip_dest_map': 'View live route',
          'trip_card': 'No cash collection is required.',
          'trip_cash': 'Collect payment after completing the trip.',
          'trip_voucher': 'Voucher ride',
          'trip_alcohol1': 'Designated-driver service 1',
          'trip_alcohol2': 'Designated-driver service 2',
          'trip_complete': 'Complete Trip',
          'trip_complete_modal_title': 'Complete this trip?',
          'trip_complete_modal_body':
              'Trip details will no longer be available after completion.',
          'trip_rest': 'Take a Break',
          'trip_wait': 'Start Waiting',
          'trip_wait_body':
              'Confirm to enter the driver queue and receive requests.',
          'trip_complete!': 'Trip Complete!',
          'trip_safe_thanks': 'Thank you for driving safely.',
          'trip_customer_cancel': 'Passenger Cancelled',
          'trip_customer_cancel_body':
              'The passenger cancelled. Return to the driver queue?',
          'Dialog_Close': 'Close',
          'trip_history_header': 'Trip History',
          'trip_history_earned': 'Total Earnings',
          'trip_history_today': 'Today',
          'trip_history_week': '7 Days',
          'trip_history_month': 'This Month',
          'trip_history_last_month': 'Last Month',
          'trip_history_total': 'All',
          'dest_location_header': 'Set Destination',
          'dest_location_hint': 'Enter a destination',
          'dest_location_button': 'Save',
          'drivernumber': 'Driver',
          'driver_number_label': 'Driver #@number',
          'Home_Today': 'Today',
          'Home_Logout': 'Logout',
          'note': 'Note',
          'choose_map': 'Choose a navigation app',
          'location_permission': 'Location access is required',
          'location_permission_retry': 'Enable current location',
          'location_permission_description':
              'Set location access to Always in Settings to receive nearby requests.',
          'appsetting': 'Open Settings',
        },
      };
}
